### ISSUE TITLE
Filtering doesn't work.

### ISSUE THREAD

**Issue by shashi007** [sereneblue/coindexter#1]
I tried to list only 10 coins and remove unmineable coins, It's not working, returns the same page. also can it be configured to display only mineable coins right when i open the page(without any filtering)?

**Comment by sereneblue** [comment]
Hello there shahsi007,

The number of currencies to display option is really the maximum number of currencies to display. coindexter uses that number for the limit parameter of coinmarketcap's API. I've set the minimum value for that option to 100 (to mimic's cmc's homepage). I'll lower it to 10 instead. Just want to make sure that if someone filters out the unmineable currencies, there will still be some shown on the page.

If you want to only display the mineable coins when you open the page, you need to use the page's URL after you've filtered it.
https://sereneblue.github.io/coindexter/#USD-100-t

The parameters after the hash symbol are your settings.
{base currency}-{max number to display}-{remove unmineable (t/f)}

**Comment by shashi007** [comment]
Thanks!
