### ISSUE TITLE
Not working on mobile devices

### ISSUE THREAD

**Issue by AKprisonER** [sereneblue/coindexter#2]
Not working on chrome android
 Tested on Mi, Moto g5 plus, lenovo vibe note

**Comment by sereneblue** [comment]
Hello there AKprisonER,

At the moment, coindexter is not fully responsive for mobile devices. I'm a little surprised it doesn't work. I just tried loading it in Chrome on Android as well and it seems like there's some JS that's not loading or it can't reach an API. I'll look into this soon.

**Comment by sereneblue** [comment]
Found the issue. Seems like older Chrome versions on Android don't have support for arrow functions. I'll have to rewrite some code to get it working.

**Comment by sereneblue** [comment]
Should work now athough the page isn't optimized for smaller devices.

**Comment by AKprisonER** [comment]
yeah.e.....working fine..but optimization is not done it seems..i will try with tat
